apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v1
  namespace: cdps-29           # AÑADIR: namespace requerido
  labels:
    app: reviews
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v1
  template:
    metadata:
      labels:
        app: reviews
        version: v1
    spec:
      containers:
      - name: reviews
        image: cdps-reviews:v1-g29  # CAMBIAR: <GROUP_NUMBER>/reviews-v1 → tu imagen
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        - name: SERVICE_VERSION     # AÑADIR: variable necesaria
          value: "v1"
        - name: ENABLE_RATINGS      # AÑADIR: variable necesaria
          value: "true"
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
        securityContext:
          runAsUser: 1000
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}