apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v2
  namespace: cdps-29           # AÑADIR: namespace requerido
  labels:
    app: reviews
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v2
  template:
    metadata:
      labels:
        app: reviews
        version: v2
    spec:
      containers:
      - name: reviews
        image: cdps-reviews:v2-g29  # CAMBIAR: <GROUP_NUMBER>/reviews-v2 → tu imagen
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        - name: SERVICE_VERSION     # AÑADIR
          value: "v2"
        - name: ENABLE_RATINGS      # AÑADIR
          value: "true"
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
        securityContext:
          runAsUser: 1000
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}